[package]
name = "common"
version.workspace = true
edition = "2021"

[dependencies]
libspike_rs = { path = "../libspike_rs" }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
